Repository jphacks/KB_1809, pull requests merged in 2018-10, with the labels that each got.

#36 fix PlanAdapter
  plannap-android/app/src/main/java/studio/aquatan/plannap/ui/plan/PlanAdapter.kt
Labels: bug

#49 認証情報をログインによって取得
  plannap-android/.idea/misc.xml
  plannap-android/app/build.gradle
  plannap-android/app/src/main/java/studio/aquatan/plannap/Plannap.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/Session.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/data/BaseRepository.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/data/PlanRepository.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/data/api/AuthService.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/data/api/PlanService.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/data/model/Authorization.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/data/model/LoginUser.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/di/AppModule.kt
Labels: enhancement

#52 LoginActivity追加
  plannap-android/app/src/main/AndroidManifest.xml
  plannap-android/app/src/main/java/studio/aquatan/plannap/Plannap.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/data/AuthRepository.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/data/BaseRepository.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/data/api/AuthService.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/di/ActivityModule.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/di/AppModule.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/ui/ViewModelFactory.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/ui/login/LoginActivity.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/ui/login/LoginViewModel.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/ui/login/ValidationResult.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/ui/main/MainActivity.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/ui/main/MainViewModel.kt
  plannap-android/app/src/main/res/layout/activity_login.xml
  plannap-android/app/src/main/res/values/strings.xml
Labels: enhancement

#58 minSdkVersion 23
  plannap-android/app/build.gradle
Labels: enhancement

#60 [WIP] ファボ機能の追加
  .gitignore
  plannap-android/.idea/codeStyles/Project.xml
  plannap-android/app/src/main/java/studio/aquatan/plannap/data/FavoriteRepository.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/data/api/FavoriteService.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/data/model/Favorite.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/data/model/Plan.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/di/AppModule.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/di/FragmentModule.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/ui/ViewModelFactory.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/ui/home/HomeFragment.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/ui/home/HomeViewModel.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/ui/plan/PlanAdapter.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/ui/plan/SpotAdapter.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/ui/plan/detail/PlanDetailActivity.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/ui/plan/list/PlanListFragment.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/ui/plan/list/PlanListViewModel.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/ui/plan/searchresult/PlanSearchResultActivity.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/ui/plan/searchresult/PlanSearchResultViewModel.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/view/widget/FavoriteButton.kt
  plannap-android/app/src/main/res/layout/fragment_plan_list.xml
  plannap-android/app/src/main/res/layout/item_plan.xml
  plannap-android/app/src/main/res/values/attrs.xml
Labels: enhancement

#62 PlanDetailActivityの機能拡張
  plannap-android/app/src/main/java/studio/aquatan/plannap/data/CommentRepository.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/data/model/Comment.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/data/model/Report.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/di/AppModule.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/ui/ViewModelFactory.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/ui/home/HomeFragment.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/ui/home/HomeViewModel.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/ui/plan/detail/PlanDetailActivity.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/ui/plan/detail/PlanDetailViewModel.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/ui/plan/detail/ReportAdapter.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/ui/plan/detail/SpotAdapter.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/util/DataBindingHelper.kt
  plannap-android/app/src/main/res/drawable/ic_attach_money_black_24dp.xml
  plannap-android/app/src/main/res/drawable/ic_circle_black_24dp.xml
  plannap-android/app/src/main/res/drawable/ic_edit_black_24dp.xml
  plannap-android/app/src/main/res/drawable/ic_query_builder_black_24dp.xml
  plannap-android/app/src/main/res/drawable/ic_report_black_24dp.xml
  plannap-android/app/src/main/res/drawable/ic_send_black_24dp.xml
  plannap-android/app/src/main/res/drawable/ic_today_black_24dp.xml
  plannap-android/app/src/main/res/layout/activity_plan_detail.xml
  plannap-android/app/src/main/res/layout/activity_plan_detail_legacy.xml
  plannap-android/app/src/main/res/layout/item_comment.xml
  plannap-android/app/src/main/res/layout/item_plan.xml
  plannap-android/app/src/main/res/layout/item_report.xml
  plannap-android/app/src/main/res/layout/item_spot.xml
  plannap-android/app/src/main/res/layout/item_spot_legacy.xml
  plannap-android/app/src/main/res/values/colors.xml
  plannap-android/app/src/main/res/values/dimens.xml
  plannap-android/app/src/main/res/values/strings.xml
Labels: enhancement

#64 fix api paths for versioning
  plannap-android/app/src/main/java/studio/aquatan/plannap/data/api/CommentService.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/data/api/FavoriteService.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/data/api/LocationService.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/data/api/PlanService.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/data/api/ReportService.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/data/api/SpotService.kt
  plannap-android/app/src/main/java/studio/aquatan/plannap/data/api/UserService.kt
Labels: DON'T MERGE, enhancement

#79 fix #78
  plannap-android/app/src/main/java/studio/aquatan/plannap/worker/PostPlanWorker.kt
Labels: bug
